### ISSUE TITLE
Add "lxc shell"?

### ISSUE THREAD

**Issue by intrepidsilence** [endaaman/lxd-completion-zsh#6]
Would you be willing to add the "shell" directive to this?

**Comment by endaaman** [comment]
It seems that `shell` is not a valid sub command. I checked it on version 4.4.

![Screenshot at 2020-08-14 20-18-25](https://user-images.githubusercontent.com/2020942/90244250-59579380-de6b-11ea-9e3e-f15cf7d00d62.png)

`shell`  is upcoming one?

If so, I'm developing this on Arch Linux and I will add its completion when the version come on Arch repository. If it is old sub command, I won't do.

**Comment by intrepidsilence** [comment]
You have to provide the container name that you want to open a shell on. It is valid on 4.3 and I doubt it was removed in 4.4. It was added around 2.4 and was added to the official bash completion in 2.4.1.

**Comment by endaaman** [comment]
I'm sorry. I confirmed the command dose exist. I didn't notice it because it didn't appear by `lxc help --all`.

I will add it soon.

**Comment by intrepidsilence** [comment]
Thanks very much!

**Comment by endaaman** [comment]
Done ea6a7200e1cd8aef733d97e6d9f53deb041c0bf3

**Comment by intrepidsilence** [comment]
Awesome, thanks!
